include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "lib/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/di/injection.config.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

